config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users 
  resources :users do
    resources :items, only: [:new, :create, :destroy, :edit, :update]
  end
  
  get 'welcome/index'

  root 'users#show'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true, length: { minimum: 5 }
                
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :confirmable
         
  validates_email_format_of :email
  validates :email, :password, presence: true
  validates :email, uniqueness: true
  
  has_many :items
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def new
    @item = Item.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @item = current_user.items.build(params[:name])
    @item.name = params[:items][:name]
    @item.order = current_user.items.count + 1;
    if @item.save
      flash[:notice] = "Item was saved"
      respond_to do |format|
        format.js
      end
    else
      flash.now["alert"] = "We had a problem.  Please try again."
      render :new
    end
  end
  
  def update
    @item = Item.find(params[:id])
    @item.assign_attributes(item_params)
    @item.save
    respond_to do |format|
      format.js
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.js { render :layout => false }
    end
  end
    
  private
  
  def item_params
    params.require(:item).permit(:name, :order, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user.nil?
      flash[:notice] = 'Please sign in before continuing'
      redirect_to welcome_index_path
    else
      @user = current_user
      @items = @user.items
    end
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_item.html.erb
<div class="item">
    <div class="number" data-item-id="<%= number %>" data-current-user="<%= current_user.id %>">
        <i class="fa fa-angle-up" aria-hidden="true"></i>
        <%= number %>
        <i class="fa fa-angle-down" aria-hidden="true"></i>
    </div>
    <div class="item-info">
        <div class="name" data-rails-id="<%= item.id %>">
            <%= item.name %>
        </div>
        <div class="delete">
            <%= link_to "", user_item_path(current_user, item), method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %>
        </div>
        <div class"time">
            <%= distance_of_time_in_words(Time.now, item.created_at + 7.days) + ' left' %>
        </div>
    </div>
</div>

app/views/items/_new.html.erb
<div id="add_task">
    <%= form_for :items, url: user_items_path(user_id: current_user.id), remote: true, method: :post do |f| %>
        <div>
            <%= f.text_field :name, placeholder: "Enter item name", size: 50 %>
            <%= f.submit 'Save', class: 'btn btn-primary' %>
            <%= link_to 'Back', users_show_path(current_user), class: 'btn btn-primary' %>
        </div>
    <% end %>
</div>

app/views/items/create.js.erb
$('#add_task').remove();
$('.container').show();
$('.items').append('<%= j render(@item) %>');

app/views/items/destroy.js.erb
$('.glyphicon.glyphicon-ok').bind('ajax:success', function() {
    $(this).closest('.item').remove();  
    });

app/views/items/new.js.erb
$('.container').hide().after('<%= j render(partial: 'new') %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/76a5d9991f.js"></script>
  </head>
  <body>
    <header>
      <div class="logo">
        <i class="fa fa-check-square" aria-hidden="true"></i><span>Blocitoff</span>
      </div>
      <ul>
        <% if current_user  %>
          <li>Signed in as: <%= current_user.email %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li>
            <%= link_to 'Register Now!', new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </header>
    <div class="content-container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div class="main-content">
        <%= yield %>
      </div>
    </div>
    <footer>
      <div class="logo">
        <i class="fa fa-check-square" aria-hidden="true"></i><span>Blocitoff</span>
      </div>
      <ul>
        <% if current_user  %>
          <li>Signed in as: <%= current_user.email %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Register Now!', new_user_registration_path %></li>
        <% end %>
      </ul>  
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="user-profile">
    <h2>ToDo List for <%= current_user.email %></h2>
    <div class="container">
        <div class="two">
            <h4>Created on:</h4>
            <p><%= current_user.created_at.strftime("%B %d, %Y") %></p>
        </div>
        <div class="two">
            <h4>Updated on:</h4>
            <p><%= current_user.updated_at.strftime("%B %d, %Y") %></p>
        </div>
        <div class="one">
            <%= link_to 'Edit Profile', edit_user_registration_path, style: 'color: rgba(25,190, 255, .9 ); border: 2px solid rgba(204, 20, 56, 1 ); background-color: #FFF200; border-radius: 10px; font-weight: bold', class: 'btn btn-primary' %>
        </div>
        <div class="one">
            <%= link_to 'New ToDo', new_user_item_path(user_id: current_user), remote: true, id: "add_item", class: 'btn btn-primary' %>
        </div>
    </div>
    <div class="items">
        <% @items.each_with_index do |item, number| %>
                <%= render 'items/item', item: item, number: number + 1 %>
        <% end %>
    </div>
</div>

app/views/welcome/index.html.erb
<div class="welcome">
    <h1 class="logo">Welcome to <i class="fa fa-check-square" aria-hidden="true"></i><span>Blocitoff</span></h1>
    <h2>A free todo list app to help keep you on track</h2>
    <% if current_user.nil? %>
        <h2 id="register" onclick ="blocmetrics.report('New user registeration click from homepage')"><%= link_to 'Register Now!', new_user_registration_path %></h2>
    <% end %>
</div>